### ISSUE TITLE
Changement de langue

### ISSUE THREAD

**Issue by mandalorien** [kiwille/uniguerre_v6#11]
Lorsqu'il y a un clique sur un des drapeaux , le changement de langue ne s'effectue plus , le bug est présents bien avant le commit https://github.com/kiwille/uniguerre_v6/commit/926224e1335554d55cf22494d48b6089cec0739f

**Comment by kiwille** [comment]
Confirmé. Le truc, c'est que je ne comprends pas vraiment d'ou vient le bug. Enfin on va voir...

**Comment by mandalorien** [comment]
Je vais revoir ca,  pourquoi on utiliserai pas les cookies pour les langues ?

**Comment by mandalorien** [comment]
Bon j'ai trouvé l'erreur et je l'ai corrigé : https://github.com/kiwille/uniguerre_v6/commit/5f268788e4f8a7450c356e067089dbe35cd5ac87

**Comment by kiwille** [comment]
Ok c'est noté. Je testerais cela une fois que je le pourrais.

**Comment by boermansjo** [comment]
Ok

Met vriendelijke groeten,
Jo Van de Velde-Boermans

2015-08-21 20:52 GMT+02:00 KIWILLE <notifications@github.com>:
