### ISSUE TITLE
La langue ne s'enregistre pas lors de l'inscription

### ISSUE THREAD

**Issue by mandalorien** [kiwille/uniguerre_v6#2]
Lors de mon inscription, la langue n'a pas été pris en compte. A priori, il n'enregistre pas en BDD l'id de la langue, qui devrait être à 1 pour le français, ou 2 pour l'anglais.

L'id retrouvé vaut 0 en base de données.

**Comment by kiwille** [comment]
@mandalorien tu sais si le bug est toujours d'actualité?

**Comment by mandalorien** [comment]
Bah pour ma part j'ai corrigé le problème sur ce commit 

https://github.com/kiwille/uniguerre_v6/commit/9becbfae33f8373cc67cb7572b569004b941634e

**Comment by kiwille** [comment]
Ok, ben je ferme l'issue. Si le bug revient, on ouvrira une autre issue.
