### ISSUE TITLE
Erreur lorsqu'on saisie mal ses identifiants

### ISSUE THREAD

**Issue by kiwille** [kiwille/uniguerre_v6#6]
Lors d'une saisie incorrect de ses identifiants à la connexion au jeu, une erreur apparait, et impossible de cliquer sur "Retour" (à cause de l'erreur surement)

![image](https://cloud.githubusercontent.com/assets/1839523/5906379/6053e372-a597-11e4-9952-3c0edba4a39b.png)

**Merci de créer une branche pour ce bug, sous le nom de `fix-issue-6`.**

**Comment by mandalorien** [comment]
Correction apporté
